export enum AssignmentStatusEnum {
    REQUESTED = "REQUESTED",
    PENDING_REVIEW = "PENDING_REVIEW",
    PENDING_INTERVIEW = "PENDING_INTERVIEW",
    INTERVIEW_CANCELED = "INTERVIEW_CANCELED",
    APPROVED = "APPROVED",
    CANCELED = "CANCELED",
    ACTIVE = "ACTIVE",
    PAST = "PAST"
}

