export enum EventAggregateEnum {
    FLEET_ORDER_ASSIGNMENT = "FLEET_ORDER_ASSIGNMENT",
    FLEET_ORDER_ASSIGNMENT_INTERVIEW = "FLEET_ORDER_ASSIGNMENT_INTERVIEW",
    WORK_DAY = "WORK_DAY",
    OVERRIDE_REQUEST = "OVERRIDE_REQUEST"
}

